apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mean
  creationTimestamp: null
  labels:
    io.kompose.service: database-claim2
  name: database-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
